version: '2.2'

services:
  web:
    build: ./project/Docker
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - 1337:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  redis:
    image: redis:alpine
  celery:
    build: ./project/Docker
    command: celery -A Core worker -l info
    volumes:
      - ./project:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  celery-beat:
    build: ./project/Docker
    command: celery -A Core beat -l info
    volumes:
      - ./project/:/usr/src/app/
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
  micro:
    build: ./project/Docker
    image: ubuntu:22.04
    working_dir: /Microservices/satellite-1
    command: pip3 install gunicorn flask
    command: gunicorn -w 4 --threads 2 --bind 0.0.0.0:8010 wsgi
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - 8010:8010
    depends_on:
      - web
  micro2:
    build: ./project/Docker
    image: ubuntu:22.04
    working_dir: /Microservices/satellite-2
    command: pip3 install gunicorn flask
    command: gunicorn -w 4 --threads 2 --bind 0.0.0.0:8011 wsgi
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - 8011:8011
    depends_on:
      - web