# Generated by Django 4.1.5 on 2023-01-27 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dockernumber', models.CharField(default='<docker #>', max_length=100)),
                ('casemanager', models.CharField(default='<docker #>', max_length=100)),
                ('casesupportmanager', models.CharField(default='<docker #>', max_length=100)),
                ('issuedate', models.CharField(default='<docker #>', max_length=100)),
                ('expirationdate', models.CharField(default='<docker #>', max_length=100)),
                ('IMEIs', models.CharField(default='<docker #>', max_length=100)),
                ('phonenumber', models.CharField(default='<docker #>', max_length=100)),
                ('address', models.CharField(default='<docker #>', max_length=100)),
                ('btp', models.BooleanField(default=False)),
                ('br', models.BooleanField(default=False)),
                ('both', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='<name>', max_length=250)),
                ('vendor', models.CharField(default='<vendor>', max_length=250)),
                ('service', models.CharField(default='<service>', max_length=500)),
                ('API', models.CharField(default='<api address>', max_length=100)),
                ('company_logo', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
                ('is_supported', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='<name>', max_length=250)),
                ('vendor', models.CharField(default='<vendor>', max_length=250)),
                ('nodeos', models.CharField(default='<nodeos>', max_length=250)),
                ('nodecpu', models.CharField(default='<nodecpu>', max_length=250)),
                ('noderam', models.CharField(default='<noderam>', max_length=250)),
                ('nodenic', models.CharField(default='<nodenic>', max_length=250)),
                ('nodeservices', models.CharField(default='<nodeservices>', max_length=250)),
                ('nodeports', models.CharField(default='<nodeports>', max_length=250)),
                ('API', models.CharField(default='<api address>', max_length=100)),
                ('company_logo', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
                ('is_supported', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Spread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item1', models.CharField(default='<item>', max_length=100)),
                ('item2', models.CharField(default='<item>', max_length=100)),
                ('item3', models.CharField(default='<item>', max_length=100)),
                ('item4', models.CharField(default='<item>', max_length=100)),
                ('item5', models.CharField(default='<item>', max_length=100)),
                ('x', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='<name>', max_length=250)),
                ('vendor', models.CharField(default='<vendor>', max_length=250)),
                ('systemservices', models.CharField(default='<systemservices>', max_length=250)),
                ('systemports', models.CharField(default='<systemports>', max_length=250)),
                ('service', models.CharField(default='<service>', max_length=500)),
                ('API', models.CharField(default='<api address>', max_length=100)),
                ('company_logo', models.FileField(default='settings.MEDIA_ROOT/logos/anonymous.jpg', upload_to='')),
                ('contract', models.CharField(default='<contract>', max_length=100)),
                ('is_supported', models.BooleanField(default=False)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.node')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srcip', models.CharField(default='<srcip>', max_length=100)),
                ('dstip', models.CharField(default='<dstip>', max_length=100)),
                ('srcport', models.CharField(default='<srcport>', max_length=100)),
                ('dstport', models.CharField(default='<dstport>', max_length=100)),
                ('md5hash', models.CharField(default='<md5hash>', max_length=100)),
                ('virustotalscore', models.CharField(default='<virustotalscore>', max_length=100)),
                ('internalthreatscore', models.CharField(default='<internalthreatscore>', max_length=100)),
                ('ctiscore', models.CharField(default='<ctiscore>', max_length=100)),
                ('dnsdisplayname', models.CharField(default='<dnsdisplayname>', max_length=100)),
                ('dnsresolvedname', models.CharField(default='<dnsresolvedname>', max_length=100)),
                ('payload', models.CharField(default='<payload>', max_length=100)),
                ('score', models.CharField(default='<score>', max_length=100)),
                ('link', models.CharField(default='<link>', max_length=100)),
                ('contract', models.CharField(default='<contract>', max_length=100)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.system')),
            ],
        ),
    ]
