# Generated by Django 4.1.5 on 2023-04-30 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0001_Registration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(default='', max_length=16)),
                ('level', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.DeleteModel(
            name='Case',
        ),
        migrations.RemoveField(
            model_name='node',
            name='contract',
        ),
        migrations.DeleteModel(
            name='Spread',
        ),
        migrations.RemoveField(
            model_name='event',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ctiscore',
        ),
        migrations.RemoveField(
            model_name='event',
            name='dnsdisplayname',
        ),
        migrations.RemoveField(
            model_name='event',
            name='dnsresolvedname',
        ),
        migrations.RemoveField(
            model_name='event',
            name='dstip',
        ),
        migrations.RemoveField(
            model_name='event',
            name='dstport',
        ),
        migrations.RemoveField(
            model_name='event',
            name='internalthreatscore',
        ),
        migrations.RemoveField(
            model_name='event',
            name='link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='md5hash',
        ),
        migrations.RemoveField(
            model_name='event',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='event',
            name='score',
        ),
        migrations.RemoveField(
            model_name='event',
            name='srcip',
        ),
        migrations.RemoveField(
            model_name='event',
            name='srcport',
        ),
        migrations.RemoveField(
            model_name='event',
            name='virustotalscore',
        ),
        migrations.RemoveField(
            model_name='system',
            name='node',
        ),
        migrations.RemoveField(
            model_name='system',
            name='systemports',
        ),
        migrations.AddField(
            model_name='event',
            name='component',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='rawvalue',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='redhighlimit',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='redlimitlow',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='satelliteid',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='timestamp',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='yellowhighlimit',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='yellowlimitlow',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='system',
            name='satelliteid',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.AddField(
            model_name='battery',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.system'),
        ),
    ]
