# Generated by Django 4.1.5 on 2023-05-01 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0002_battery_delete_case_remove_node_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='counter',
            field=models.IntegerField(default='0'),
        ),
        migrations.CreateModel(
            name='TSTAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tstatlevel', models.CharField(default='', max_length=16)),
                ('level', models.CharField(default='', max_length=16)),
                ('counter', models.IntegerField(default='0')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UI.system')),
            ],
        ),
    ]
