# Generated by Django 4.1.5 on 2023-05-01 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0003_battery_counter_tstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.CharField(default='', max_length=25),
        ),
    ]
